# Caso de Uso: DNS Condicional (Split DNS)
# 
# Cenário: Diferentes domínios resolvidos por servidores DNS diferentes
# - *.company.local → DNS corporativo (192.168.1.10)
# - *.aws.internal → DNS da AWS (10.0.0.2)
# - Outros domínios → DNS público (8.8.8.8)

apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-conditional
  namespace: kube-system
data:
  Corefile: |
    # Domínio corporativo
    company.local:53 {
        errors
        cache 30
        forward . 192.168.1.10 192.168.1.11 {
            max_concurrent 1000
        }
        log
    }
    
    # Domínio AWS interno
    aws.internal:53 {
        errors
        cache 30
        forward . 10.0.0.2 {
            max_concurrent 1000
        }
        log
    }
    
    # Configuração padrão (Kubernetes + Internet)
    .:53 {
        errors
        health {
            lameduck 5s
        }
        ready
        
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
            ttl 30
        }
        
        prometheus :9153
        
        forward . 8.8.8.8 8.8.4.4 {
            max_concurrent 1000
            health_check 5s
        }
        
        cache 30
        loop
        reload
        loadbalance
    }
