# Caso de Uso: Logging e Debugging Avançado
# 
# Cenário: Debugar problemas de DNS ou auditar queries

apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-logging
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        
        # Log de todas as queries
        log . {
            class all
        }
        
        health {
            lameduck 5s
        }
        ready
        
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
            ttl 30
        }
        
        prometheus :9153
        
        forward . /etc/resolv.conf {
            max_concurrent 1000
        }
        
        cache 30
        loop
        reload
        loadbalance
    }
