# Caso de Uso: CoreDNS Production-Ready
# 
# Cenário: Configuração completa e otimizada para produção
# Inclui: HA, Performance, Segurança, Observabilidade, Resiliência

apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-production
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        
        health {
            lameduck 5s
        }
        ready
        
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
            ttl 30
            endpoint_pod_names
        }
        
        prometheus :9153
        
        # Cache otimizado com prefetch
        cache 300 {
            success 10000 3600
            denial 5000 600
            prefetch 10 60s 20%
            serve_stale 86400s
        }
        
        # Forward com múltiplos upstreams e health check
        forward . 8.8.8.8 8.8.4.4 1.1.1.1 1.0.0.1 {
            max_concurrent 1000
            expire 10s
            health_check 5s
            policy random
        }
        
        loop
        reload 10s
        loadbalance round_robin
        
        # Log apenas erros
        log . {
            class denial error
        }
    }

---
# Deployment Production-Ready
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredns
  namespace: kube-system
  labels:
    k8s-app: kube-dns
spec:
  replicas: 3
  
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  
  selector:
    matchLabels:
      k8s-app: kube-dns
  
  template:
    metadata:
      labels:
        k8s-app: kube-dns
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9153"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: k8s-app
                  operator: In
                  values:
                  - kube-dns
              topologyKey: kubernetes.io/hostname
      
      priorityClassName: system-cluster-critical
      serviceAccountName: coredns
      
      tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      
      containers:
      - name: coredns
        image: coredns/coredns:1.11.1
        imagePullPolicy: IfNotPresent
        
        args: [ "-conf", "/etc/coredns/Corefile" ]
        
        volumeMounts:
        - name: config-volume
          mountPath: /etc/coredns
          readOnly: true
        
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        - containerPort: 9153
          name: metrics
          protocol: TCP
        
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - all
          readOnlyRootFilesystem: true
        
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
        
        readinessProbe:
          httpGet:
            path: /ready
            port: 8181
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
        
        resources:
          limits:
            memory: 512Mi
            cpu: 500m
          requests:
            cpu: 200m
            memory: 256Mi
      
      volumes:
      - name: config-volume
        configMap:
          name: coredns-production
          items:
          - key: Corefile
            path: Corefile
      
      dnsPolicy: Default

---
# HorizontalPodAutoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: coredns
  namespace: kube-system
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: coredns
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80

---
# PodDisruptionBudget
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: coredns
  namespace: kube-system
spec:
  minAvailable: 2
  selector:
    matchLabels:
      k8s-app: kube-dns
