apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secrets
  namespace: applications
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ""
    keyvaultName: akvsimsecrets
    cloudName: "AzurePublicCloud"
    tenantId: 8b7290e2-e841-4992-bdea-21f802bed815
    objects: |
      array:
        - |
          objectName: DB-USER
          objectType: secret
          objectVersion: ""
        - |
          objectName: DB-PASSWORD
          objectType: secret
          objectVersion: ""
        - |
          objectName: REDIS-PASSWORD
          objectType: secret
          objectVersion: ""
        - |
          objectName: API-KEY
          objectType: secret
          objectVersion: ""
        - |
          objectName: API-SECRET
          objectType: secret
          objectVersion: ""
        - |
          objectName: SMTP-USER
          objectType: secret
          objectVersion: ""
        - |
          objectName: SMTP-PASSWORD
          objectType: secret
          objectVersion: ""
        - |
          objectName: JWT-SECRET
          objectType: secret
          objectVersion: ""
        - |
          objectName: SSH-PRIVATE-KEY
          objectType: secret
          objectVersion: ""
        - |
          objectName: PAYMENT-GATEWAY-KEY
          objectType: secret
          objectVersion: ""
        - |
          objectName: OAUTH-CLIENT-ID
          objectType: secret
          objectVersion: ""
        - |
          objectName: OAUTH-CLIENT-SECRET
          objectType: secret
          objectVersion: ""
  secretObjects:
  - secretName: fake-app-secrets
    type: Opaque
    data:
    - objectName: DB-USER
      key: DB_USER
    - objectName: DB-PASSWORD
      key: DB_PASSWORD
    - objectName: REDIS-PASSWORD
      key: REDIS_PASSWORD
    - objectName: API-KEY
      key: API_KEY
    - objectName: API-SECRET
      key: API_SECRET
    - objectName: SMTP-USER
      key: SMTP_USER
    - objectName: SMTP-PASSWORD
      key: SMTP_PASSWORD
    - objectName: JWT-SECRET
      key: JWT_SECRET
    - objectName: SSH-PRIVATE-KEY
      key: SSH_PRIVATE_KEY
    - objectName: PAYMENT-GATEWAY-KEY
      key: PAYMENT_GATEWAY_KEY
    - objectName: OAUTH-CLIENT-ID
      key: OAUTH_CLIENT_ID
    - objectName: OAUTH-CLIENT-SECRET
      key: OAUTH_CLIENT_SECRET
