apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secrets
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"                # Deprecated, usar workloadIdentity para novos clusters
    useVMManagedIdentity: "true"           # Se estiver usando Managed Identity do nó
    userAssignedIdentityID: ""             # Opcional, se usar uma identidade gerenciada atribuída ao usuário
    keyvaultName: akvforakssim             # Nome do Key Vault
    cloudName: ""                          # Vazio = Azure global. Usar "AzureUSGovernment" se for gov.
    objects: |
      array:
        - |
          objectName: my-secret            # Nome do segredo no Key Vault
          objectType: secret               # Tipo: secret, key, ou cert
          objectVersion: ""                # Versão opcional, vazio pega a última
        - |
          objectName: my-cert              # Outro exemplo (certificado)
          objectType: cert
          objectVersion: ""
    tenantId: <TENANT_ID>                  # Substituir pelo tenant real

  secretObjects:                           # Cria secret nativo do Kubernetes a partir do Key Vault
  - secretName: my-secret-k8s
    type: Opaque
    data:
    - objectName: my-secret
      key: my-secret-key
