apiVersion: v1
kind: Pod
metadata:
  name: busybox-test
  namespace: applications
spec:
  containers:
  - name: busybox
    image: busybox
    command: [ "sleep", "3600" ]
    volumeMounts:
    - name: secrets-store-inline
      mountPath: "/mnt/secrets-store"
      readOnly: true
    envFrom:
    - secretRef:
        name: fake-app-secrets   # Secret criado pelo SecretProviderClass
  volumes:
  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "azure-kv-secrets"
