apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-users-rolebinding-pod-list-role
  namespace: homologacao
subjects:
- kind: ServiceAccount
  name: sysadmin
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-list-role
  apiGroup: rbac.authorization.k8s.io